'use client';

import { useEffect, useState } from 'react';
import { supabase } from '@/lib/supabase';

export default function AdminPage() {
  const [session, setSession] = useState(null);
  const [login, setLogin] = useState({ email: '', password: '' });
  const [bookings, setBookings] = useState([]);
  const [courses, setCourses] = useState([]);
  const [message, setMessage] = useState('');
  const [courseForm, setCourseForm] = useState({ title:'', subtitle:'', description:'', price:'', duration:'60分钟', target_group:'少儿、青少年', features:'一对一指导,课后反馈', sort_order:10 });

  useEffect(() => { supabase.auth.getSession().then(({ data }) => { setSession(data.session); if (data.session) refresh(); }); }, []);

  async function signIn(e) { e.preventDefault(); setMessage(''); const { data, error } = await supabase.auth.signInWithPassword(login); if (error) { setMessage('登录失败：' + error.message); return; } setSession(data.session); refresh(); }
  async function signOut() { await supabase.auth.signOut(); setSession(null); }
  async function refresh() { const [{ data: b }, { data: c }] = await Promise.all([supabase.from('bookings').select('*').order('created_at',{ascending:false}), supabase.from('courses').select('*').order('sort_order',{ascending:true})]); setBookings(b||[]); setCourses(c||[]); }
  async function updateStatus(id,status){ await supabase.from('bookings').update({status}).eq('id',id); refresh(); }
  async function deleteBooking(id){ if(!confirm('确定删除这个预约吗？')) return; await supabase.from('bookings').delete().eq('id',id); refresh(); }
  async function addCourse(e){ e.preventDefault(); const payload={...courseForm, price:Number(courseForm.price||0), features:courseForm.features.split(',').map(x=>x.trim()).filter(Boolean), sort_order:Number(courseForm.sort_order||10), is_active:true}; const { error }=await supabase.from('courses').insert([payload]); if(error){setMessage('添加课程失败：'+error.message);return;} setCourseForm({title:'',subtitle:'',description:'',price:'',duration:'60分钟',target_group:'少儿、青少年',features:'一对一指导,课后反馈',sort_order:10}); refresh(); }
  async function toggleCourse(course){ await supabase.from('courses').update({is_active:!course.is_active}).eq('id',course.id); refresh(); }
  async function deleteCourse(id){ if(!confirm('确定删除课程吗？')) return; await supabase.from('courses').delete().eq('id',id); refresh(); }

  if(!session){ return <main className="admin-page"><div className="container"><div className="card" style={{maxWidth:480,margin:'80px auto'}}><span className="kicker">Admin</span><h1 style={{fontSize:42}}>后台登录</h1><form className="form" onSubmit={signIn}><label>邮箱<input className="input" value={login.email} onChange={e=>setLogin({...login,email:e.target.value})}/></label><label>密码<input className="input" type="password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/></label><button className="btn primary full">登录后台</button>{message && <div className="notice error">{message}</div>}</form></div></div></main>; }

  return <main className="admin-page"><div className="container"><div className="admin-bar"><div><span className="kicker">Dashboard</span><h1 style={{fontSize:42,margin:'12px 0'}}>后台管理</h1></div><button className="btn" onClick={signOut}>退出登录</button></div>{message&&<div className="notice error">{message}</div>}<section className="card"><h2>预约客户</h2><div className="table-wrap"><table className="table"><thead><tr><th>时间</th><th>家长</th><th>电话/微信</th><th>孩子</th><th>目标</th><th>区域</th><th>状态</th><th>操作</th></tr></thead><tbody>{bookings.map(b=><tr key={b.id}><td>{new Date(b.created_at).toLocaleString()}</td><td>{b.parent_name}</td><td>{b.phone}<br/>{b.wechat}</td><td>{b.child_age} · {b.child_gender}</td><td>{b.training_goal}<br/><span style={{color:'#b7c3d7'}}>{b.notes}</span></td><td>{b.address_area}<br/>{b.preferred_time}</td><td><span className="status">{b.status}</span></td><td><select className="select" value={b.status} onChange={e=>updateStatus(b.id,e.target.value)}><option value="new">new</option><option value="contacted">contacted</option><option value="scheduled">scheduled</option><option value="done">done</option><option value="lost">lost</option></select><button className="danger" onClick={()=>deleteBooking(b.id)}>删除</button></td></tr>)}</tbody></table></div></section><section className="section"><div className="grid two"><div className="card"><h2>添加课程</h2><form className="form" onSubmit={addCourse}><label>课程名称<input className="input" value={courseForm.title} onChange={e=>setCourseForm({...courseForm,title:e.target.value})}/></label><label>副标题<input className="input" value={courseForm.subtitle} onChange={e=>setCourseForm({...courseForm,subtitle:e.target.value})}/></label><label>描述<textarea className="textarea" value={courseForm.description} onChange={e=>setCourseForm({...courseForm,description:e.target.value})}/></label><div className="form-row"><label>价格<input className="input" value={courseForm.price} onChange={e=>setCourseForm({...courseForm,price:e.target.value})}/></label><label>排序<input className="input" value={courseForm.sort_order} onChange={e=>setCourseForm({...courseForm,sort_order:e.target.value})}/></label></div><label>特色标签，逗号分隔<input className="input" value={courseForm.features} onChange={e=>setCourseForm({...courseForm,features:e.target.value})}/></label><button className="btn primary full">添加课程</button></form></div><div className="card"><h2>课程管理</h2><div className="table-wrap"><table className="table" style={{minWidth:520}}><thead><tr><th>课程</th><th>价格</th><th>状态</th><th>操作</th></tr></thead><tbody>{courses.map(c=><tr key={c.id}><td>{c.title}<br/><span style={{color:'#b7c3d7'}}>{c.subtitle}</span></td><td>¥{c.price}</td><td>{c.is_active?'显示':'隐藏'}</td><td><button className="btn" onClick={()=>toggleCourse(c)}>{c.is_active?'隐藏':'显示'}</button><button className="danger" onClick={()=>deleteCourse(c.id)}>删除</button></td></tr>)}</tbody></table></div></div></div></section></div></main>;
}
